server:
  port: 8080

spring:
  profiles:
    include: oauth
  application:
    name: back
  # DB Link
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/GCH_MGR?serverTimezone=UTC&characterEncoding=UTF-8
    username: GCH_MGR
    password: Jaehyun1!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true