spring:
  config:
    import:
      - classpath:/config/application/application-${spring.profiles.active}.yml
  application:
    name: back
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true


logging:
  config: classpath:/config/log4j2/log4j2-${spring.profiles.active}.xml
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.querydsl.jpa: DEBUG
    com.gch.back: DEBUG
