server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/GCH_MGR?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: GCH_MGR
    password: Jaehyun1!
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    
  # Kafka Configuration
  kafka:
    bootstrap-servers: kafka-stg-server-1:9092,kafka-stg-server-2:9092,kafka-stg-server-3:9092
    consumer:
      group-id: gch-stg-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    topics:
      main: gch-stg-topic
      retry: gch-stg-retry-topic
      dead: gch-stg-dlt-topic